# fly.toml app configuration file generated for cool-sun-3799 on 2023-08-22T14:47:53-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "cool-sun-3799"
primary_region = "dfw"

[build]

[env]
  PORT = "3000" # add this

[http_service]
  internal_port = 3000 # ensure that this is same as PORT
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
